// export const certifications = [
//   {
//     title: "Full Stack Web Development (0-100)",
//     issuer: "100xDevs (Harkirat Singh)",
//     date: "Jun 2024",
//     description:
//       "Advanced deep-dive into industrial-grade engineering. Covers high-scale backend (Redis, Kafka, gRPC), monorepos, and cloud-native deployment with Docker and Kubernetes.",
//     tags: ["Next.js", "PostgreSQL", "TurboRepo", "System Design", "DevOps"],
//     verifyUrl:
//       "https://drive.google.com/file/d/11H6LcU3OLUHgsVGzgdo1V-RD4tIbrgQ\_/view?usp=share\_link",
//   },
//   {
//     title: "Programming with Rust",
//     issuer: "Coursera (Professional Certificate)",
//     date: "Jan 2026",
//     description:
//       "Mastered memory safety through ownership/borrowing and advanced concurrency. Built scalable web services using Actix-web and Rocket with deep-dive into systems-level performance.",
//     tags: ["Rust", "Actix", "Rocket", "Concurrency", "Systems Programming"],
//     verifyUrl: "https://coursera.org/verify/specialization/92MEOJMIZ19H",
//   },
//   {
//     title: "Microsoft Python Development",
//     issuer: "Microsoft (via Coursera)",
//     date: "Jan 2026",
//     description:
//       "Professional track covering clean code, automation scripting, and web development with Flask. Integrated generative AI tools and cloud deployment via Azure into the dev workflow.",
//     tags: ["Python", "Flask", "Automation", "Azure", "Data Analysis"],
//     verifyUrl: "https://coursera.org/verify/professional-cert/IIEM3AQLP01H",
//   },
//   {
//     title: "Machine Learning Specialization",
//     issuer: "DeepLearning.AI & Stanford (Andrew Ng)",
//     date: "Oct 2024",
//     description:
//       "Built supervised and unsupervised models from scratch. Specialized in Neural Networks with TensorFlow, Decision Trees, and advanced Recommender Systems using collaborative filtering.",
//     tags: [
//       "TensorFlow",
//       "Scikit-Learn",
//       "Neural Networks",
//       "Reinforcement Learning",
//     ],
//     verifyUrl: "https://coursera.org/verify/specialization/9R8ZRBH3I4L8",
//   },
// ];

export const certifications = [
  {
    title: "Full Stack Web Development (0-100)",
    issuer: "100xDevs (Harkirat Singh)",
    date: "Jun 2024",
    description:
      "Comprehensive full-stack engineering program covering JavaScript foundations to advanced system design. Built scalable backend systems using Node.js, Express, PostgreSQL, MongoDB, Redis, Kafka, and gRPC. Implemented authentication, rate limiting, WebSockets, and real-time systems. Worked with monorepos (TurboRepo), Docker, Kubernetes, CI/CD, and AWS (EC2, S3, EKS, Load Balancers). Completed production-grade projects including Paytm Wallet, Zerodha, and Zapier clones with horizontal scaling, sharding, replication, and CAP theorem concepts.",
    tags: [
      "JavaScript",
      "TypeScript",
      "Node.js",
      "Express",
      "Next.js",
      "React",
      "PostgreSQL",
      "MongoDB",
      "Redis",
      "Kafka",
      "gRPC",
      "System Design",
      "Docker",
      "Kubernetes",
      "AWS",
      "CI/CD",
      "WebSockets",
      "Tailwind",
      "Monorepo",
      "DevOps",
      "Scalability",
    ],
    verifyUrl:
      "https://drive.google.com/file/d/11H6LcU3OLUHgsVGzgdo1V-RD4tIbrgQ_/view?usp=share_link",
  },
  {
    title: "Programming with Rust",
    issuer: "Coursera (Professional Certificate)",
    date: "Jan 2026",
    description:
      "Mastered Rust for systems programming and high-performance backend development. Applied ownership, borrowing, and lifetimes to ensure memory safety without garbage collection. Built concurrent and multithreaded applications, optimized performance, and implemented scalable web services using Rocket and Actix. Completed real-world projects including a multithreaded web scraper and crypto price tracker with async handling and database integration.",
    tags: [
      "Rust",
      "Ownership Model",
      "Concurrency",
      "Multithreading",
      "Actix",
      "Rocket",
      "Systems Programming",
      "Async Programming",
      "Web Services",
      "Performance Optimization",
      "Memory Safety",
      "Backend Development",
    ],
    verifyUrl: "https://coursera.org/verify/specialization/92MEOJMIZ19H",
  },
  {
    title: "Microsoft Python Development",
    issuer: "Microsoft (via Coursera)",
    date: "Jan 2026",
    description:
      "Professional Python track covering core programming, automation, data analysis, and web development. Built RESTful APIs using Flask, automated workflows, integrated generative AI tools, and deployed applications on Microsoft Azure. Completed hands-on projects including data analysis pipelines, ML-based sports prediction models, and chatbot-based real-time analytics systems.",
    tags: [
      "Python",
      "Flask",
      "Automation",
      "Pandas",
      "Matplotlib",
      "REST APIs",
      "Azure",
      "Cloud Deployment",
      "Machine Learning",
      "Data Analysis",
      "Generative AI",
      "Git",
      "DevOps",
      "Web Scraping",
    ],
    verifyUrl: "https://coursera.org/verify/professional-cert/IIEM3AQLP01H",
  },
  {
    title: "Machine Learning Specialization",
    issuer: "DeepLearning.AI & Stanford (Andrew Ng)",
    date: "Oct 2024",
    description:
      "Completed the full Machine Learning Specialization covering supervised learning (linear/logistic regression, neural networks, decision trees), unsupervised learning (clustering, anomaly detection), recommender systems, and reinforcement learning. Built models using NumPy, Scikit-learn, and TensorFlow, applied feature engineering, model evaluation, and ML best practices to solve real-world predictive problems.",
    tags: [
      "Machine Learning",
      "Deep Learning",
      "TensorFlow",
      "Scikit-Learn",
      "NumPy",
      "Neural Networks",
      "Decision Trees",
      "Random Forest",
      "Reinforcement Learning",
      "Recommender Systems",
      "Feature Engineering",
      "Model Evaluation",
      "Unsupervised Learning",
      "Artificial Intelligence",
    ],
    verifyUrl: "https://coursera.org/verify/specialization/9R8ZRBH3I4L8",
  },
];
