export const projectCategories = [
  "All",
  "Full Stack",
  "Frontend",
  "Backend",
  "Mobile",
  "AI/ML",
];
export const projects = [
  {
    id: 1,
    title: "Canvasly",
    description:
      "Canvasly is a real-time collaborative whiteboard application with realtime chat, built with Next.js, WebSockets, and a scalable Turborepo architecture.",
    image: "canvasly.png",
    technologies: [
      "Express.js",
      "Next.js",
      "Websocket",
      "Prisma ORM",
      "Tailwind CSS",
      "Nodemailer",
      "Docker",
      "Zod",
      "Next-auth",
    ],
    category: "Full Stack",
    liveUrl: "https://canvasly-web-seven.vercel.app/",
    githubUrl: "https://github.com/manish01101/Canvasly",
    featured: true,
    year: "February 2026",
  },
  {
    id: 5,
    title: "ResQPlate",
    description:
      "ResQPlate is a production-grade, location-based food rescue platform designed to bridge the gap between food donors (restaurants, events, individuals) and registered NGOs/volunteers. By leveraging real-time geospatial tracking, smart routing algorithms, and secure handoff protocols, ResQPlate ensures surplus food reaches those in need before it expires.",
    image: "resqplate.png",
    technologies: [
      "Express.js",
      "React.js",
      "Websocket",
      "Leaflet",
      "Tailwind CSS",
      "OpenStreetMap API",
      "Leaflet Routing Machine",
    ],
    category: "Full Stack",
    liveUrl: "https://resqplate-tan.vercel.app",
    githubUrl: "https://github.com/manish01101/ResQPlate",
    featured: true,
    year: "July 2026",
  },
  {
    id: 6,
    title: "SyncMeet",
    description:
      "SyncMeet is a modern, enterprise-ready, peer-to-peer video conferencing application.",
    image: "syncmeet.png",
    technologies: [
      "Express.js",
      "Next.js",
      "Websocket",
      "WebRTC",
      "Tailwind CSS",
    ],
    category: "Full Stack",
    liveUrl: "https://sync-meet-orpin.vercel.app",
    githubUrl: "https://github.com/manish01101/SyncMeet",
    featured: true,
    year: "May 2026",
  },
  {
    id: 2,
    title: "blogg",
    description: "A full-stack blogging platform.",
    image: "blogg.png",
    technologies: [
      "React.js",
      "TypeScript",
      "Hono",
      "PostgreSQL",
      "Tailwind CSS",
      "Prisma",
      "Cloudflare worker",
    ],
    category: "Full Stack",
    liveUrl: "https://blogg-cyan-mu.vercel.app",
    githubUrl: "https://github.com/manish01101/blogg",
    featured: true,
    year: "March 2025",
  },
  {
    id: 3,
    title: "Game Store",
    description:
      "A responsive game discovery platform built with React, TypeScript, and Chakra UI. Features dark theme UI, genre filtering, platform selection, and sorting. Powered by a third-party REST API for dynamic game data.",
    image: "game_store.png",
    technologies: ["React.js", "TypeScript", "Chakra UI", "REST API"],
    category: "Frontend",
    liveUrl: "https://game-store-wheat-one.vercel.app/",
    githubUrl: "https://github.com/manish01101/game-store",
    featured: false,
    year: "July 2024",
  },
  {
    id: 4,
    title: "Weather App",
    description:
      "A small weather application that fetches current weather and simple forecasts from a public weather API. Use it to look up conditions by city or coordinates.",
    image: "weather_app.png",
    technologies: ["React.js", "JavaScript", "REST API"],
    category: "Frontend",
    liveUrl: "https://weather-app-five-eta-63.vercel.app/",
    githubUrl: "https://github.com/manish01101/Weather-App",
    featured: false,
    year: "August 2024",
  },
];
